# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  matrix:
    - DJANGO_VERSION=dj17
    - DJANGO_VERSION=dj18
    - DJANGO_VERSION=dj19
    - DJANGO_VERSION=dj110

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION=dj17

install:
  - pip install tox

# command to run tests using coverage, e.g. python setup.py test
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//./}-${DJANGO_VERSION},coverage

# report coverage to coveralls.io
after_success: coveralls

notifications:
  slack: tobalabs:XPt5OlsKuFGgIQZp0DpNXBUl
